// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Navigation → Items*
 */
export interface NavigationDocumentDataItemsItem {
  /**
   * Label field in *Navigation → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Navigation → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Items field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<NavigationDocumentDataItemsItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Primary content in *Page → Slice Zone → Hero Fullscreen → Primary*
 */
export interface PageDocumentDataSlicesHeroFullscreenSlicePrimary {
  /**
   * Background Image field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Video URL field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io video URL
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Mobile Video URL field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io mobile video URL (optional)
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.mobile_video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  mobile_video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Title field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter title...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subtitle...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Primary Button Text field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter primary button text...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.primary_cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_text: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select primary button destination...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter secondary button text...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.secondary_cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_text: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Page → Slice Zone → Hero Fullscreen → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select secondary button destination...
   * - **API ID Path**: page.slices[].hero_fullscreen.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesHeroFullscreenSlice = prismic.Slice<
  "hero_fullscreen",
  Simplify<PageDocumentDataSlicesHeroFullscreenSlicePrimary>,
  never
>;

/**
 * Item content in *Page → Slice Zone → Trust Bar → Items*
 */
export interface PageDocumentDataSlicesTrustBarSliceItem {
  /**
   * Icon field in *Page → Slice Zone → Trust Bar → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].trust_bar.items.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Text field in *Page → Slice Zone → Trust Bar → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter trust indicator text...
   * - **API ID Path**: page.slices[].trust_bar.items.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesTrustBarSlice = prismic.Slice<
  "trust_bar",
  Record<string, never>,
  Simplify<PageDocumentDataSlicesTrustBarSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Benefits → Primary*
 */
export interface PageDocumentDataSlicesBenefitsSlicePrimary {
  /**
   * Title field in *Page → Slice Zone → Benefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title...
   * - **API ID Path**: page.slices[].benefits.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Page → Slice Zone → Benefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section subtitle...
   * - **API ID Path**: page.slices[].benefits.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA Text field in *Page → Slice Zone → Benefits → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text...
   * - **API ID Path**: page.slices[].benefits.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page → Slice Zone → Benefits → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select button destination...
   * - **API ID Path**: page.slices[].benefits.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item content in *Page → Slice Zone → Benefits → Items*
 */
export interface PageDocumentDataSlicesBenefitsSliceItem {
  /**
   * Icon field in *Page → Slice Zone → Benefits → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].benefits.items.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Page → Slice Zone → Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter benefit title...
   * - **API ID Path**: page.slices[].benefits.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Page → Slice Zone → Benefits → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter benefit description...
   * - **API ID Path**: page.slices[].benefits.items.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesBenefitsSlice = prismic.Slice<
  "benefits",
  Simplify<PageDocumentDataSlicesBenefitsSlicePrimary>,
  Simplify<PageDocumentDataSlicesBenefitsSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Solutions → Primary*
 */
export interface PageDocumentDataSlicesSolutionsSlicePrimary {
  /**
   * Section Title field in *Page → Slice Zone → Solutions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title...
   * - **API ID Path**: page.slices[].solutions.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item content in *Page → Slice Zone → Solutions → Items*
 */
export interface PageDocumentDataSlicesSolutionsSliceItem {
  /**
   * Image field in *Page → Slice Zone → Solutions → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].solutions.items.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *Page → Slice Zone → Solutions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter solution subtitle...
   * - **API ID Path**: page.slices[].solutions.items.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Text field in *Page → Slice Zone → Solutions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter solution description...
   * - **API ID Path**: page.slices[].solutions.items.text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * CTA Text field in *Page → Slice Zone → Solutions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text...
   * - **API ID Path**: page.slices[].solutions.items.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page → Slice Zone → Solutions → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select button destination...
   * - **API ID Path**: page.slices[].solutions.items.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesSolutionsSlice = prismic.Slice<
  "solutions",
  Simplify<PageDocumentDataSlicesSolutionsSlicePrimary>,
  Simplify<PageDocumentDataSlicesSolutionsSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Process → Primary*
 */
export interface PageDocumentDataSlicesProcessSlicePrimary {
  /**
   * Section Title field in *Page → Slice Zone → Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title...
   * - **API ID Path**: page.slices[].process.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Text field in *Page → Slice Zone → Process → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text...
   * - **API ID Path**: page.slices[].process.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page → Slice Zone → Process → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select button destination...
   * - **API ID Path**: page.slices[].process.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item content in *Page → Slice Zone → Process → Items*
 */
export interface PageDocumentDataSlicesProcessSliceItem {
  /**
   * Step Icon field in *Page → Slice Zone → Process → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].process.items.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Step Title field in *Page → Slice Zone → Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter step title...
   * - **API ID Path**: page.slices[].process.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Step Description field in *Page → Slice Zone → Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter step description...
   * - **API ID Path**: page.slices[].process.items.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesProcessSlice = prismic.Slice<
  "process",
  Simplify<PageDocumentDataSlicesProcessSlicePrimary>,
  Simplify<PageDocumentDataSlicesProcessSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Testimonials → Primary*
 */
export interface PageDocumentDataSlicesTestimonialsSlicePrimary {
  /**
   * Section Title field in *Page → Slice Zone → Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title...
   * - **API ID Path**: page.slices[].testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item content in *Page → Slice Zone → Testimonials → Items*
 */
export interface PageDocumentDataSlicesTestimonialsSliceItem {
  /**
   * Author Image field in *Page → Slice Zone → Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[].testimonials.items.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Quote field in *Page → Slice Zone → Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter testimonial quote...
   * - **API ID Path**: page.slices[].testimonials.items.quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * Author Name field in *Page → Slice Zone → Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter author name...
   * - **API ID Path**: page.slices[].testimonials.items.author_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_name: prismic.KeyTextField;

  /**
   * Author Location field in *Page → Slice Zone → Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter author location...
   * - **API ID Path**: page.slices[].testimonials.items.author_location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author_location: prismic.KeyTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesTestimonialsSlice = prismic.Slice<
  "testimonials",
  Simplify<PageDocumentDataSlicesTestimonialsSlicePrimary>,
  Simplify<PageDocumentDataSlicesTestimonialsSliceItem>
>;

/**
 * Primary content in *Page → Slice Zone → Call To Action Full → Primary*
 */
export interface PageDocumentDataSlicesCallToActionFullSlicePrimary {
  /**
   * Title field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter title...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subtitle...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * CTA Text field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter button text...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select button destination...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Phone Number field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter phone number...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Email Address field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter email address...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Service Area field in *Page → Slice Zone → Call To Action Full → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter service area...
   * - **API ID Path**: page.slices[].call_to_action_full.primary.service_area
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_area: prismic.KeyTextField;
}

/**
 * Slice for *Page → Slice Zone*
 */
export type PageDocumentDataSlicesCallToActionFullSlice = prismic.Slice<
  "call_to_action_full",
  Simplify<PageDocumentDataSlicesCallToActionFullSlicePrimary>,
  never
>;

type PageDocumentDataSlicesSlice =
  | ReviewsSlice
  | PlansSlice
  | PageDocumentDataSlicesHeroFullscreenSlice
  | PageDocumentDataSlicesTrustBarSlice
  | PageDocumentDataSlicesBenefitsSlice
  | PageDocumentDataSlicesSolutionsSlice
  | PageDocumentDataSlicesProcessSlice
  | PageDocumentDataSlicesTestimonialsSlice
  | PageDocumentDataSlicesCallToActionFullSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_text: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Video Backgrounds documents
 */
interface VideoBackgroundsDocumentData {
  /**
   * Video URL field in *Video Backgrounds*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io video URL
   * - **API ID Path**: video_backgrounds.video_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Mobile Video URL field in *Video Backgrounds*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io mobile video URL (optional)
   * - **API ID Path**: video_backgrounds.mobile_video_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  mobile_video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Video Backgrounds document from Prismic
 *
 * - **API ID**: `video_backgrounds`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoBackgroundsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VideoBackgroundsDocumentData>,
    "video_backgrounds",
    Lang
  >;

export type AllDocumentTypes =
  | NavigationDocument
  | PageDocument
  | SettingsDocument
  | VideoBackgroundsDocument;

/**
 * Primary content in *Hero Fullscreen → Default → Primary*
 */
export interface HeroFullscreenSliceDefaultPrimary {
  /**
   * Title field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter title text...
   * - **API ID Path**: hero_fullscreen.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subtitle text...
   * - **API ID Path**: hero_fullscreen.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Primary Button Text field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter primary button text...
   * - **API ID Path**: hero_fullscreen.default.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link...
   * - **API ID Path**: hero_fullscreen.default.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter secondary button text...
   * - **API ID Path**: hero_fullscreen.default.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link...
   * - **API ID Path**: hero_fullscreen.default.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Video URL field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io video URL
   * - **API ID Path**: hero_fullscreen.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Mobile Video URL field in *Hero Fullscreen → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter the ImageKit.io mobile video URL (optional)
   * - **API ID Path**: hero_fullscreen.default.primary.mobile_video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  mobile_video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Fullscreen Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroFullscreenSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroFullscreenSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero Fullscreen*
 */
type HeroFullscreenSliceVariation = HeroFullscreenSliceDefault;

/**
 * Hero Fullscreen Shared Slice
 *
 * - **API ID**: `hero_fullscreen`
 * - **Description**: Full screen hero section with video background
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroFullscreenSlice = prismic.SharedSlice<
  "hero_fullscreen",
  HeroFullscreenSliceVariation
>;

/**
 * Item in *Plans → Default → Primary → Badges*
 */
export interface PlansSliceDefaultPrimaryBadgesItem {
  /**
   * Icon field in *Plans → Default → Primary → Badges*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.badges[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *Plans → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.badges[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Sub Label field in *Plans → Default → Primary → Badges*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.badges[].sublabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sublabel: prismic.KeyTextField;
}

/**
 * Item in *Plans → Default → Primary → Plans*
 */
export interface PlansSliceDefaultPrimaryPlansItem {
  /**
   * Image field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Price field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Features (one per line) field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].features
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  features: prismic.KeyTextField;

  /**
   * CTA Text field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Plans → Default → Primary*
 */
export interface PlansSliceDefaultPrimary {
  /**
   * Section Title field in *Plans → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nuestros Planes
   * - **API ID Path**: plans.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Plans → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Elige el plan que más se adapte a ti
   * - **API ID Path**: plans.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_subtitle: prismic.KeyTextField;

  /**
   * Badges field in *Plans → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.badges[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  badges: prismic.GroupField<Simplify<PlansSliceDefaultPrimaryBadgesItem>>;

  /**
   * Plans field in *Plans → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  plans: prismic.GroupField<Simplify<PlansSliceDefaultPrimaryPlansItem>>;
}

/**
 * Default variation for Plans Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlansSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlansSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Plans*
 */
type PlansSliceVariation = PlansSliceDefault;

/**
 * Plans Shared Slice
 *
 * - **API ID**: `plans`
 * - **Description**: Pricing/Plans section with badges, left copy, and plan cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlansSlice = prismic.SharedSlice<"plans", PlansSliceVariation>;

/**
 * Item in *Reviews → Default → Primary → Reviews*
 */
export interface ReviewsSliceDefaultPrimaryReviewsItem {
  /**
   * Pool Image field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[].pool_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  pool_image: prismic.ImageField<never>;

  /**
   * Client Name field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: María González
   * - **API ID Path**: reviews.default.primary.reviews[].client_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_name: prismic.KeyTextField;

  /**
   * Rating (1-5) field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5
   * - **API ID Path**: reviews.default.primary.reviews[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;

  /**
   * Review Text field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Excelente servicio, mi piscina nunca había estado tan limpia...
   * - **API ID Path**: reviews.default.primary.reviews[].review_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  review_text: prismic.KeyTextField;

  /**
   * City field in *Reviews → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Miami, FL
   * - **API ID Path**: reviews.default.primary.reviews[].city
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  city: prismic.KeyTextField;
}

/**
 * Primary content in *Reviews → Default → Primary*
 */
export interface ReviewsSliceDefaultPrimary {
  /**
   * Section Title field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lo que dicen nuestros clientes
   * - **API ID Path**: reviews.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Testimonios reales de familias satisfechas
   * - **API ID Path**: reviews.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_subtitle: prismic.KeyTextField;

  /**
   * Main Pool Image field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Reviews field in *Reviews → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  reviews: prismic.GroupField<Simplify<ReviewsSliceDefaultPrimaryReviewsItem>>;
}

/**
 * Default variation for Reviews Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Reviews*
 */
type ReviewsSliceVariation = ReviewsSliceDefault;

/**
 * Reviews Shared Slice
 *
 * - **API ID**: `reviews`
 * - **Description**: Customer reviews section with main image and testimonial carousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsSlice = prismic.SharedSlice<
  "reviews",
  ReviewsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataItemsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesHeroFullscreenSlicePrimary,
      PageDocumentDataSlicesTrustBarSliceItem,
      PageDocumentDataSlicesBenefitsSlicePrimary,
      PageDocumentDataSlicesBenefitsSliceItem,
      PageDocumentDataSlicesSolutionsSlicePrimary,
      PageDocumentDataSlicesSolutionsSliceItem,
      PageDocumentDataSlicesProcessSlicePrimary,
      PageDocumentDataSlicesProcessSliceItem,
      PageDocumentDataSlicesTestimonialsSlicePrimary,
      PageDocumentDataSlicesTestimonialsSliceItem,
      PageDocumentDataSlicesCallToActionFullSlicePrimary,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      VideoBackgroundsDocument,
      VideoBackgroundsDocumentData,
      AllDocumentTypes,
      HeroFullscreenSlice,
      HeroFullscreenSliceDefaultPrimary,
      HeroFullscreenSliceVariation,
      HeroFullscreenSliceDefault,
      PlansSlice,
      PlansSliceDefaultPrimaryBadgesItem,
      PlansSliceDefaultPrimaryPlansItem,
      PlansSliceDefaultPrimary,
      PlansSliceVariation,
      PlansSliceDefault,
      ReviewsSlice,
      ReviewsSliceDefaultPrimaryReviewsItem,
      ReviewsSliceDefaultPrimary,
      ReviewsSliceVariation,
      ReviewsSliceDefault,
    };
  }
}
