// Code generated by Slice Machine. DO NOT EDIT.

import HeroFullscreen from "./HeroFullscreen";
import Plans from "./Plans";
import Reviews from "./Reviews";
import FAQ from "./FAQ";
import ContactAlternate from "./ContactAlternate";
import VideoSection from "./VideoSection";

export const components = {
  hero_fullscreen: HeroFullscreen,
  plans: Plans,
  reviews: Reviews,
  faq: FAQ,
  contact_alternate: ContactAlternate,
  video_section: VideoSection,
};
