// Code generated by Slice Machine. DO NOT EDIT.

import HeroFullscreen from "./HeroFullscreen";
import Plans from "./Plans";
import Reviews from "./Reviews";
import FAQ from "./FAQ";

export const components = {
  hero_fullscreen: HeroFullscreen,
  plans: Plans,
  reviews: Reviews,
  faq: FAQ,
};
