// Code generated by Slice Machine. DO NOT EDIT.

import HeroFullscreen from "./HeroFullscreen";
import Plans from "./Plans";

export const components = {
  hero_fullscreen: HeroFullscreen,
  plans: Plans,
};
